"""Add performance indexes

Revision ID: 842535b7916f
Revises: 4057f9e802e1
Create Date: 2025-12-03 22:01:50.902479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842535b7916f'
down_revision: Union[str, None] = '4057f9e802e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_embedding_id', 'chunks', ['embedding_id'], unique=False)
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index('idx_documents_uploaded_by_status', 'documents', ['uploaded_by', 'status'], unique=False)
    op.create_index('idx_qa_created_at', 'qa_history', ['created_at'], unique=False)
    op.create_index('idx_qa_session_id', 'qa_history', ['session_id'], unique=False)
    op.create_index('idx_qa_user_id', 'qa_history', ['user_id'], unique=False)
    op.create_index('idx_qa_user_session', 'qa_history', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qa_user_session', table_name='qa_history')
    op.drop_index('idx_qa_user_id', table_name='qa_history')
    op.drop_index('idx_qa_session_id', table_name='qa_history')
    op.drop_index('idx_qa_created_at', table_name='qa_history')
    op.drop_index('idx_documents_uploaded_by_status', table_name='documents')
    op.drop_index('idx_documents_uploaded_by', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_index('idx_chunks_embedding_id', table_name='chunks')
    op.drop_index('idx_chunks_document_id', table_name='chunks')
    # ### end Alembic commands ###
